server:
  port: ${port:8000}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    
spring:
  security:
    user:
      name: test
      password: 1234
    oauth2:
      client:
        registration:
          naver:
            client-id: Eb5H1V64heK1YUH5gEAl
            client-secret: 24grRHZO0D
            scope:
            - email
            - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://web-study.cpxqancqhi5t.ap-northeast-2.rds.amazonaws.com:3306/noonee?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true"
    username: admin
    password: 1q2w3e4r
    
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
    
mybatis:
  mapper-locations:
  - /mappers/*.xml

file: #변수처럼 만듬
  path: E:/bosung/bosung/Project-NOONEE/upload/img/